### PR TITLE
teach_word_view update guide, tab bar, await

### PR DESCRIPTION
**Pull request by ining310**
1. update bpmf svg
2. disable button when the previous steps aren't completed
3. disable tab switched by pressing TabBar
4. enable next step only if the sounds end
---
- db getPhraseId error
- progressBar
- bpmf quiz code is not the lastest

### CODE REVIEW

**Comment by dlion168** [comment]
There are 2 issues:
1. Overflow in "用一用"
Screenshot_20231022-232920
2. Can you please explain why does button "重新" appears in this page? 
Screenshot_20231022-233035

**Comment by ining310** [comment]
> There are 2 issues:
> 
> 1. Overflow in "用一用"
>    Screenshot_20231022-232920
> 2. Can you please explain why does button "重新" appears in this page?
>    Screenshot_20231022-233035

2. do you mean since the users don't need to correct all the strokes in once, "重新" doesn't need to exist? (I think this make sense, I can just remove this button)

**Comment by dlion168** [comment]
Yes, it would be great if you can make this modification.

**Review by dlion168 — APPROVED** [review]
LGTM, leave some adjustment next time

**Pull request merged**
